version: "3.8"
services:
  db:
    image: postgres:13
    container_name: books_db_container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - books_network

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram_bot_container
    environment:
      - BOT_TOKEN=7828869023:AAHv5nHMayfWrHgBxM2u4uI7G5-hHN6JSK8
      - DB_URL=postgresql://user:password@db:5432/books_db
    depends_on:
      - db
    networks:
      - books_network

volumes:
  pg_data:

networks:
  books_network:
    driver: bridge
